# Default values for steadybit-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

agent:
  # agent.key -- The secret token which your agent uses to authenticate to steadybit's servers. Get it from  Get it from https://platform.steadybit.io/settings/agents/setup.
  key: null

  # agent.registerUrl -- The URL of the steadybit server your agents will connect to.
  registerUrl: https://platform.steadybit.io
  # agent.additionalVolumes -- Additional volumes to which the agent container will be mounted.
  #  - name: tmp # Volume's name.
  #    mountPath: /tmp # Path within the container at which the volume should be mounted.
  #    hostPath: /tmp # Pre-existing file or directory on the host machine
  additionalVolumes: []
  # agent.containerRuntime -- The container runtime to be used. Valid values:
  #    docker     = uses the docker runtime.
  #                 Will mount [/var/run/docker.sock]
  #
  #    crio       = uses the cri-o runtime.
  #                 Will mount [/run/crio/crio.sock, /run/runc]
  #
  #    containerd = uses the containerd runtime.
  #                 Will mount [/run/containerd/containerd.sock, /run/containerd/runc/k8s.io]
  #
  containerRuntime: docker
  # agent.containerRuntimeSocket -- use this to override the host path for the container runtime socket to mount. By default it is derived from containerRuntime
  containerRuntimeSocket: null
  # agent.runcRoot -- use this to override the host path for the runc root path to mount. By default it is derived from containerRuntime
  runcRoot: null

  # agent.env -- Additional environment variables for the steadybit agent
  env: {}
  # agent.extraLabels -- Additional labels
  extraLabels: {}

cluster:
  # cluster.name Represents the name that will be assigned to this Kubernetes cluster in steadybit
  name: null

image:
  # image.name -- The container image to use of the steadybit agent.
  name: docker.steadybit.io/steadybit/agent
  # image.tag -- tag name of the agent container image to use.
  tag: latest
  # image.pullPolicy -- Specifies when to pull the image container.
  pullPolicy: Always
  registry: {}

priorityClassName:
  # priorityClassName.use -- use a priorityClassName
  use: false
  # priorityClassName.name -- The name of the priority class to be used
  name: high-priority

resources:
  requests:
    # requests.memory -- The minimal amount of memory needed
    memory: "512Mi"
    # requests.cpu -- The minimal amount of cpu shares needed
    cpu: "250m"
  limits:
    # requests.memory -- The limit of memory to be used
    memory: "768Mi"
    # requests.cpu -- The limit of cpu share to be used during its interval
    cpu: "1500m"

updateStrategy:
  # updateStrategy.type -- Which type of `updateStrategy` should be used.
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1

rbac:
  # rbac.create -- Specifies whether RBAC resources should be created.
  create: true
  # rbac.readonly -- Specifies if Kubernetes API access should only be read only.
  readonly: false

serviceAccount:
  # serviceAccount.create -- Specifies whether a ServiceAccount should be created.
  create: true
  # serviceAccount.name -- The name of the ServiceAccount to use. If not set and `create` is true, a name is generated using the fullname template.
  name: steadybit-agent

# podAnnotations -- Additional annotations to be added to the agent pods.
podAnnotations: {}

podSecurityPolicy:
  # podSecurityPolicy.enable -- Specifies whether a PodSecurityPolicy should be authorized for the steadybit Agent pods.
  # Requires `rbac.create` to be `true` as well.
  enable: false

  # podSecurityPolicy.name -- The name of an existing PodSecurityPolicy you would like to authorize for the steadybit Agent pods.
  # If not set and `enable` is true, a PodSecurityPolicy will be created with a name generated using the fullname template.
  name: null

# nodeSelector -- Node labels for pod assignment
nodeSelector: {}

# tolerations -- Tolerations to influence agent pod assignment.
tolerations: []

# affinity -- Affinities to influence agent pod assignment.
affinity: {}
