{{- if .Values.agent.key -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "steadybit-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.agent.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  selector:
    matchLabels:
  {{- include "steadybit-agent.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.updateStrategy.type }}
    {{- if eq .Values.updateStrategy.type "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.updateStrategy.rollingUpdate.maxUnavailable }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "steadybit-agent.commonLabels" . | nindent 8 }}
      {{- range $key, $value := .Values.agent.extraLabels }}
        {{ $key }}: {{ $value }}
      {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "steadybit-agent.serviceAccountName" . }}
      hostIPC: true
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirstWithHostNet
      {{ if .Values.priorityClassName.use }}
      priorityClassName: {{ .Values.priorityClassName.name }}
      {{ end }}
      containers:
        - name: steadybit-agent
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          env:
            - name: STEADYBIT_AGENT_REGISTER_URL
              value: {{ .Values.agent.registerUrl | quote }}
            - name: STEADYBIT_AGENT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "steadybit-agent.fullname" . }}
                  key: key
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- range $key, $value := .Values.agent.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          securityContext:
            privileged: true
          volumeMounts:
            - name: steadybit-agent-state
              mountPath: /var/lib/steadybit-agent
            - name: container-sock
              mountPath: {{ include "container-sock" . }}
            - name: cgroup-root
              mountPath: /sys/fs/cgroup
              readOnly: true
            {{- if include "runc-root" . }}
            - name: runc-root
              mountPath: {{ include "runc-root" . }}
            {{- end }}
            {{- if .Values.agent.additionalVolumes }}
            {{- range $index,$backend := .Values.agent.additionalVolumes }}
            {{ $volumeIndex :=add $index 2 -}}
            - name: {{ $backend.name }}
              mountPath: {{ $backend.mountPath }}
            {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: docker-steadybit-io
      volumes:
        - name: steadybit-agent-state
          hostPath:
            path: /var/lib/steadybit-agent
        - name: container-sock
          hostPath:
            path: {{ include "container-sock" . }}
        - name: cgroup-root
          hostPath:
            path: /sys/fs/cgroup
        {{- if include "runc-root" . }}
        - name: runc-root
          hostPath:
            path: {{ include "runc-root" . }}
        {{- end }}
        {{- if .Values.agent.additionalVolumes }}
        {{- range $index,$backend := .Values.agent.additionalVolumes }}
        {{ $volumeIndex :=add $index 2 -}}
        - name: {{ $backend.name }}
          hostPath:
            path: {{ $backend.hostPath }}
  {{- end }}
  {{- end }}
  {{- end -}}