{{- if .Values.rbac.create -}}
  {{- if (and .Values.podSecurityPolicy.enable (not .Values.podSecurityPolicy.name)) -}}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "steadybit-agent.podSecurityPolicyName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "steadybit-agent.commonLabels" . | nindent 4 }}
  {{- range $key, $value := .Values.agent.extraLabels }}
    {{ $key }}: {{ $value }}
  {{- end }}
spec:
  privileged: true
  allowPrivilegeEscalation: true
  allowedHostPaths:
    - pathPrefix: /var/lib/steadybit-agent
      readOnly: false
    - pathPrefix: {{ include "container-sock-host-path" . }}
      readOnly: false
    - pathPrefix: /sys/fs/cgroup
      readOnly: true
    {{- if include "runc-root" . }}
    - pathPrefix: {{ include "runc-root-host-path" . }}
      readOnly: false
    {{- end }}
  volumes:
    - configMap
    - downwardAPI
    - emptyDir
    - persistentVolumeClaim
    - secret
    - projected
    - hostPath
  hostNetwork: true
  hostPorts:
    - min: 0
      max: 65535
  hostIPC: true
  hostPID: true
  runAsUser:
    rule: "RunAsAny"
  seLinux:
    rule: "RunAsAny"
  supplementalGroups:
    rule: "RunAsAny"
  fsGroup:
    rule: "RunAsAny"
  {{- end -}}
  {{- end -}}